import {
  FaWifi, FaTv, FaSwimmingPool, FaParking, FaUtensils, FaDog, FaSmokingBan, FaHotTub, FaFireExtinguisher, FaFirstAid, FaKey, FaUsers, FaBed, FaSuitcaseRolling, FaWheelchair, FaDoorOpen, FaNetworkWired, FaCalendarAlt, FaChild, FaGlassCheers, FaTshirt, FaPumpSoap, FaSoap, FaWind, FaLaptop, FaUserTie, FaUmbrellaBeach, FaWater, FaThermometerHalf, FaFire, FaBath, FaChargingStation, FaPlug, FaLightbulb, FaRoad, FaShieldAlt, FaHourglassHalf, FaMoon, FaFaucet,
} from 'react-icons/fa'
import { FiCoffee } from 'react-icons/fi'
import { BiBlanket } from "react-icons/bi"
import { GiHanger } from "react-icons/gi"
import { FaElevator } from 'react-icons/fa6'
import { MdFitnessCenter, MdOutlineLiveTv, MdOutlineWifi, MdAcUnit, MdAlarm, MdSensorDoor, MdBalcony } from 'react-icons/md'

export const amenityIcons = {
  'TV': FaTv,
  'Cable TV': MdOutlineLiveTv,
  'Internet': MdOutlineWifi,
  'Wifi': FaWifi,
  'Air conditioning': MdAcUnit,
  'AC': MdAcUnit,
  'Wheelchair accessible': FaWheelchair,
  'Pool': FaSwimmingPool,
  'Kitchen': FaUtensils,
  'Free parking on premises': FaParking,
  'Free parking': FaParking,
  'Doorman': FaUserTie,
  'Gym': MdFitnessCenter,
  'Elevator': FaElevator,
  'Hot tub': FaHotTub,
  'Jacuzzi': FaHotTub,
  'Heating': FaThermometerHalf,
  'Family/kid friendly': FaChild,
  'Suitable for events': FaGlassCheers,
  'Washer': FaSoap,
  'Dryer': FaTshirt,
  'Smoke detector': FaShieldAlt,
  'Carbon monoxide detector': MdAlarm,
  'First aid kit': FaFirstAid,
  'Safety card': FaShieldAlt,
  'Fire extinguisher': FaFireExtinguisher,
  'Essentials': FaBath,
  'Shampoo': FaPumpSoap,
  '24-hour check-in': FaHourglassHalf,
  'Hangers': GiHanger,
  'Hair dryer': FaWind,
  'Iron': FaTshirt,
  'Laptop friendly workspace': FaLaptop,
  'Self check-in': FaKey,
  'Building staff': FaUsers,
  'Private entrance': MdSensorDoor,
  'Room-darkening shades': FaMoon,
  'Hot water': FaFaucet,
  'Bed linens': FaBed,
  'Extra pillows and blankets': BiBlanket,
  'Ethernet connection': FaNetworkWired,
  'Luggage dropoff allowed': FaSuitcaseRolling,
  'Long term stays allowed': FaCalendarAlt,
  'Ground floor access': MdSensorDoor,
  'Wide hallway clearance': FaWheelchair,
  'Step-free access': FaWheelchair,
  'Wide doorway': MdSensorDoor,
  'Flat path to front door': FaRoad,
  'Well-lit path to entrance': FaLightbulb,
  'Disabled parking spot': FaParking,
  'Wide clearance to bed': FaBed,
  'Wide entryway': MdSensorDoor,
  'Waterfront': FaWater,
  'Beachfront': FaUmbrellaBeach,
  'Pet friendly': FaDog,
  'No smoking': FaSmokingBan,
  'EV charger': FaChargingStation,
  'BBQ': FaFire,
  'Fireplace': FaFire,
  'Coffee maker': FiCoffee,
  'Lake Access': FaWater,
  'Balcony': MdBalcony,
}