import { LiaHotTubSolid, LiaSmokingBanSolid, LiaSnowflake, LiaSwimmingPoolSolid } from "react-icons/lia"
import { LuAccessibility, LuUtensilsCrossed, LuCircleParking, LuUserCheck, LuDumbbell, LuThermometer, LuBaby, LuCalendarCheck, LuWind, LuShieldCheck, LuFlame, LuDroplet, LuClock, LuLaptop, LuKey, LuDoorOpen, LuMoon, LuShowerHead, LuBedDouble, LuNetwork, LuCalendarClock, LuRoute, LuLightbulb, LuPlugZap, LuCoffee, LuLandPlot, LuTvMinimal, LuWifi, LuAlarmSmoke, LuMicrowave, LuUtensils, LuChefHat, LuLayoutGrid, LuHandshake } from 'react-icons/lu'
import { MdOutlineBeachAccess } from "react-icons/md"
import { PiCoatHangerLight, PiElevatorLight, PiFireExtinguisherLight, PiFirstAidKitLight, PiGlobeLight, PiHandSoapLight, PiPawPrintLight, PiSuitcaseLight, PiTelevisionLight, PiWashingMachineLight, PiWavesLight } from "react-icons/pi"
import { RiGroup3Line } from "react-icons/ri"
import { TbFridge, TbIroning3 } from "react-icons/tb"

export const amenityIcons = {
  'TV': LuTvMinimal,
  'Cable TV': PiTelevisionLight,
  'Internet': PiGlobeLight,
  'Wifi': LuWifi,
  'Air conditioning': LiaSnowflake,
  'AC': LiaSnowflake,
  'Wheelchair accessible': LuAccessibility,
  'Pool': LiaSwimmingPoolSolid,
  'Kitchen': LuUtensilsCrossed,
  'Free parking on premises': LuCircleParking,
  'Free street parking': LuCircleParking,
  'Free parking': LuCircleParking,
  'Doorman': LuUserCheck,
  'Gym': LuDumbbell,
  'Elevator': PiElevatorLight,
  'Hot tub': LiaHotTubSolid,
  'Jacuzzi': LiaHotTubSolid,
  'Heating': LuThermometer,
  'Family/kid friendly': LuBaby,
  'Suitable for events': LuCalendarCheck,
  'Washer': PiWashingMachineLight,
  'Dryer': LuWind,
  'Smoke detector': LuAlarmSmoke,
  'Carbon monoxide detector': LuAlarmSmoke,
  'First aid kit': PiFirstAidKitLight,
  'Safety card': LuShieldCheck,
  'Fire extinguisher': PiFireExtinguisherLight,
  'Essentials': PiHandSoapLight,
  'Shampoo': LuDroplet,
  '24-hour check-in': LuClock,
  'Hangers': PiCoatHangerLight,
  'Hair dryer': LuWind,
  'Iron': TbIroning3,
  'Laptop friendly workspace': LuLaptop,
  'Self check-in': LuKey,
  'Building staff': RiGroup3Line,
  'Private entrance': LuDoorOpen,
  'Room-darkening shades': LuMoon,
  'Hot water': LuShowerHead,
  'Bed linens': LuBedDouble,
  'Extra pillows and blankets': LuBedDouble,
  'Ethernet connection': LuNetwork,
  'Luggage dropoff allowed': PiSuitcaseLight,
  'Long term stays allowed': LuCalendarClock,
  'Ground floor access': LuDoorOpen,
  'Wide hallway clearance': LuAccessibility,
  'Step-free access': LuAccessibility,
  'Wide doorway': LuDoorOpen,
  'Flat path to front door': LuRoute,
  'Well-lit path to entrance': LuLightbulb,
  'Disabled parking spot': LuCircleParking,
  'Wide clearance to bed': LuBedDouble,
  'Wide entryway': LuDoorOpen,
  'Waterfront': PiWavesLight,
  'Beachfront': MdOutlineBeachAccess,
  'Pet friendly': PiPawPrintLight,
  'No smoking': LiaSmokingBanSolid,
  'EV charger': LuPlugZap,
  'BBQ': LuFlame,
  'Fireplace': LuFlame,
  'Coffee maker': LuCoffee,
  'Lake Access': PiWavesLight,
  'Balcony': LuLandPlot,
  'Microwave': LuMicrowave,
  'Refrigerator': TbFridge,
  'Dishes and silverware': LuUtensils,
  'Cooking basics': LuChefHat,
  'Stove': LuFlame,
  'Single level home': LuLayoutGrid,
  'Host greets you': LuHandshake,
  'Handheld shower head': LuShowerHead,
}